/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cooltrickshome_ImageResolver */

#ifndef _Included_com_cooltrickshome_ImageResolver
#define _Included_com_cooltrickshome_ImageResolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cooltrickshome_ImageResolver
 * Method:    getKeys
 * Signature: (II)V
 */
JNIEXPORT jint JNICALL Java_com_cooltrickshome_ImageResolver_getKeys
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif


